kind: pipeline
type: kubernetes
name: jenkins-agent-docker

concurrency:
  limit: 1

steps:
- name: Docker  
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: craftingit/jenkins-agent-docker
    context: Container/docker/
    dockerfile: Container/docker/Dockerfile
    auto_tag: true

----
kind: pipeline
type: kubernetes
name: jenkins-agent-javamaven

concurrency:
  limit: 1

steps:    
- name: JavaMaven  
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: craftingit/jenkins-agent-javamaven
    context: Container/javamaven/
    dockerfile: Container/javamaven/Dockerfile
    auto_tag: true

----
kind: pipeline
type: kubernetes
name: jenkins-agent-releaser

concurrency:
  limit: 1

steps:    
- name: Releaser 
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: craftingit/jenkins-agent-releaser
    context: Container/releaser/
    dockerfile: Container/releaser/Dockerfile
    auto_tag: true 

----
kind: pipeline
type: kubernetes
name: jenkins-agent-dotnet

concurrency:
  limit: 1

steps:    
- name: Dotnet 
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: craftingit/jenkins-agent-dotnet
    context: Container/dotnet/
    dockerfile: Container/dotnet/Dockerfile
    auto_tag: true

----
kind: pipeline
type: kubernetes
name: jenkins-agent-javascript

concurrency:
  limit: 1

steps:    
- name: javascript 
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: craftingit/jenkins-agent-javascript
    context: Container/javascript/
    dockerfile: Container/javascript/Dockerfile
    auto_tag: true

----
kind: pipeline
type: kubernetes
name: jenkins-agent-dotnetblazor

concurrency:
  limit: 1

steps:    
- name: dotnetblazor 
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: craftingit/jenkins-agent-dotnetblazor
    context: Container/dotnetblazor/
    dockerfile: Container/dotnetblazor/Dockerfile
    auto_tag: true

----
kind: pipeline
type: kubernetes
name: jenkins-agent-javaandroid

concurrency:
  limit: 1

steps:   
- name: javaandroid 
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: craftingit/jenkins-agent-javaandroid
    context: Container/javaandroid/
    dockerfile: Container/javaandroid/Dockerfile
    auto_tag: true

----
kind: pipeline
type: kubernetes
name: jenkins-agent-javaandroidcordova

concurrency:
  limit: 1

steps:  
- name: javaandroidcordova 
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: craftingit/jenkins-agent-javaandroidcordova
    context: Container/javaandroidcordova/
    dockerfile: Container/javaandroidcordova/Dockerfile
    auto_tag: true