sudo: required
language: bash
services:
  - docker

script:
- docker build -t agent-docker Container/docker/ 
- docker build -t agent-javamaven Container/javamaven/ 
- docker build -t agent-nodejs Container/nodejs/ 
- docker build -t agent-yarn Container/yarn/ 

deploy:
  - provider: script
    env: TRAVIS_TAG=dev
    script: bash .ci/docker_push_tag.sh 
    on:
      branch: master

  - provider: script
    script: bash docker_push_tag.sh
    on:
      tags: true