sudo: required
language: bash
services:
  - docker

jobs:
include:
  - stage: build docker
    script:
      - docker build -t agent-docker Container/docker/ 
  - stage: build javamaven
    script:
      - docker build -t agent-docker Container/javamaven/ 
  - stage: build javamaven
    script:
      - docker build -t agent-docker Container/javamaven/ 
  - stage: build yarn
    script:
      - docker build -t agent-docker Container/yarn/ 

deploy:
  - provider: script
    script: bash .ci/docker_push_dev.sh
    on:
      branch: master

  - provider: script
    script: bash .ci/docker_push_tag.sh
    on:
      tags: true
