sudo: required
language: bash
services:
  - docker

stages:
  - build
  - name: dev-deploy
    if: branch = master
  - name: deploy
    if: tags = true

jobs:
  include:
    - stage: build 
      script: docker build -t agent-docker Container/docker/ 
    -  
      script: docker build -t agent-javamaven Container/javamaven/ 
    -
      script: docker build -t agent-nodejs Container/nodejs/ 
    -
      script: docker build -t agent-yarn Container/yarn/ 
    - stage: dev-deploy 
      env: TRAVIS_TAG=dev
      script: bash .ci/docker_push_tag.sh 
    - stage: deploy 
      script: bash .ci/docker_push_tag.sh 