sudo: required
language: bash
services:
  - docker

script:
  - docker build -t agent-docker Container/docker/
  - docker build -t agent-javamaven Container/javamaven/
  - docker build -t agent-releaser Container/releaser/
  - docker build -t agent-dotnet Container/dotnet/
  - docker build -t agent-releaser Container/releaser/

deploy:
  - provider: script
    script: bash .ci/docker_push_dev.sh
    on:
      branch: master

  - provider: script
    script: bash .ci/docker_push_tag.sh
    on:
      tags: true
