sudo: required
language: bash
services:
  - docker

jobs:
  include:
    - stage: build 
      script: docker build -t agent-docker Container/docker/ 
      script: docker build -t agent-docker Container/javamaven/ 
      script: docker build -t agent-docker Container/nodejs/ 
      script: docker build -t agent-docker Container/yarn/ 
      
deploy:
  - provider: script
    script: bash .ci/docker_push_dev.sh
    on:
      branch: master

  - provider: script
    script: bash .ci/docker_push_tag.sh
    on:
      tags: true
