sudo: required
language: bash
services:
  - docker

script:
  - docker build -t agent-docker Container/docker/ 

deploy:
  - provider: script
    script: bash .ci/docker_push_dev.sh
    on:
      branch: master

  - provider: script
    script: bash .ci/docker_push_tag.sh
    on:
      tags: true
