version: 1

update_configs:
  - package_manager: "docker"
    directory: "/Container/docker"
    update_schedule: "weekly"
  - package_manager: "docker"
    directory: "/Container/dotnet"
    update_schedule: "weekly"
  - package_manager: "docker"
    directory: "/Container/javamaven"
    update_schedule: "weekly"
  - package_manager: "docker"
    directory: "/Container/nodejs"
    update_schedule: "weekly"
  - package_manager: "docker"
    directory: "/Container/yarn"
    update_schedule: "weekly"
